//------------------------------------------------------
// THIS FILE IS AUTOGENERATED
// DO NOT APPLY MANUAL MODIFICATIONS IN THIS FILE!
//------------------------------------------------------

const sqlite3 = require("sqlite3").verbose();
const uuid = require('uuid');
const dbHelper = require('../../../../helpers/dbManager');
const logger = require('../../../../helpers/logger');

async function getIdByGuid(guid) {
    logger.log("usersProvider->getIdByGuid called with guid " + guid);
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        const result = await new Promise((resolve, reject) => {
            db.serialize(() => {
                db.get(`SELECT id FROM users WHERE guid=? LIMIT 1`, [guid], (error, row) => {
                    if (error) {
                        logger.error("usersProvider->getIdByGuid SQL Error: " + error.message);
                        return reject(error);
                    }

                    if (row) {
                        logger.log("usersProvider->getIdByGuid returned row obj " + JSON.stringify(row));
                        resolve(row.id);
                    } else {
                        logger.log("usersProvider->getIdByGuid record not found");
                        resolve(null);
                    }
                });
            });
        });
        db.close();
        return result;
    } catch (error) {
        logger.error("usersProvider->getIdByGuid error: " + error.message);
        throw error;
    }
}


// getByGuid
async function getByGuid(params) {
    logger.log("usersProvider->getByGuid Started: " + JSON.stringify(params));
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        const result = await new Promise((resolve, reject) => {
            let resultObject = {};
            logger.log("usersProvider->getByGuid Started with params: " + JSON.stringify(params));

            db.serialize(() => {
                db.each(`SELECT * FROM users WHERE guid=? AND id IS NOT NULL AND isDeleted=0`, [params.guid,],
                    (error, row) => {
                        if (error) {
                            logger.error(error.message);
                            return reject(error);
                        }
                        let recordToReturn = 				{
					id: row.id,
					guid: row.guid,
					email: row.email,
					displayName: row.displayName,
				};
                        resultObject = recordToReturn; // Since it's a single result, we overwrite resultObject
                    },
                    (err) => {
                        if (err) {
                            logger.error(err.message);
                            return reject(err);
                        }
                        logger.log("usersProvider->getByGuid Finished (Promise resolved)");
                        resolve(resultObject);
                    }
                );
            });
        });
        db.close();
        logger.log("usersProvider->getByGuid this is the result: " + JSON.stringify(result));
        return result;
    } catch (error) {
        logger.error("usersProvider->getByGuid error: " + error.message);
        throw error;
    }
}


// listForGrid
async function listForGrid(params) {
    logger.log("usersProvider->listForGrid Started: " + JSON.stringify(params));
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        const result = await new Promise((resolve, reject) => {
            let resultsArray = [];
            logger.log("usersProvider->listForGrid Started with params: " + JSON.stringify(params));
            db.serialize(() => {
                db.each(`SELECT * FROM users WHERE isDeleted=0`, [],
                    (error, row) => {
                        if (error) {
                            logger.error(error.message);
                            return reject(error);
                        }
                        let recordToReturn = 				{
					guid: row.guid,
					email: row.email,
					displayName: row.displayName,
				};
                        resultsArray.push(recordToReturn);
                    },
                    (err) => {
                        if (err) {
                            logger.error(err.message);
                            return reject(err);
                        }
                        logger.log("usersProvider->listForGrid Finished (Promise resolved)");
                        resolve(resultsArray);
                    }
                );
            });
        });
        db.close();
        logger.log("usersProvider->listForGrid this is the result: " + JSON.stringify(result));
        return result;
    } catch (error) {
        logger.error("usersProvider->listForGrid error: " + error.message);
        throw error;
    }
}


// listForDropdown
async function listForDropdown(params) {
    logger.log("usersProvider->listForDropdown Started: " + JSON.stringify(params));
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        const result = await new Promise((resolve, reject) => {
            let resultsArray = [];
            logger.log("usersProvider->listForDropdown Started with params: " + JSON.stringify(params));
            db.serialize(() => {
                db.each(`SELECT * FROM users WHERE isDeleted=0`, [],
                    (error, row) => {
                        if (error) {
                            logger.error(error.message);
                            return reject(error);
                        }
                        let recordToReturn = 				{
					guid: row.guid,
					displayName: row.displayName,
				};
                        resultsArray.push(recordToReturn);
                    },
                    (err) => {
                        if (err) {
                            logger.error(err.message);
                            return reject(err);
                        }
                        logger.log("usersProvider->listForDropdown Finished (Promise resolved)");
                        resolve(resultsArray);
                    }
                );
            });
        });
        db.close();
        logger.log("usersProvider->listForDropdown this is the result: " + JSON.stringify(result));
        return result;
    } catch (error) {
        logger.error("usersProvider->listForDropdown error: " + error.message);
        throw error;
    }
}


// listAll
async function listAll(params) {
    logger.log("usersProvider->listAll Started: " + JSON.stringify(params));
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        const result = await new Promise((resolve, reject) => {
            let resultsArray = [];
            logger.log("usersProvider->listAll Started with params: " + JSON.stringify(params));
            db.serialize(() => {
                db.each(`SELECT * FROM users `, [],
                    (error, row) => {
                        if (error) {
                            logger.error(error.message);
                            return reject(error);
                        }
                        let recordToReturn = 				{
					id: row.id,
					guid: row.guid,
					email: row.email,
					displayName: row.displayName,
					password: row.password,
					isDeleted: row.isDeleted,
				};
                        resultsArray.push(recordToReturn);
                    },
                    (err) => {
                        if (err) {
                            logger.error(err.message);
                            return reject(err);
                        }
                        logger.log("usersProvider->listAll Finished (Promise resolved)");
                        resolve(resultsArray);
                    }
                );
            });
        });
        db.close();
        logger.log("usersProvider->listAll this is the result: " + JSON.stringify(result));
        return result;
    } catch (error) {
        logger.error("usersProvider->listAll error: " + error.message);
        throw error;
    }
}


// save
async function save(params) {
    logger.log("usersProvider->save Started: " + JSON.stringify(params));
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        if (params.id > 0) {
            // Update existing record
            await new Promise((resolve, reject) => {
                db.serialize(() => {
                    logger.log("usersProvider->save(update) Started");
                    db.prepare(`UPDATE users SET email=?,displayName=? WHERE id=?`, [params.email,params.displayName,params.id])
                      .run((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                      })
                      .finalize((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                          resolve();
                      });
                });
            });
            logger.log("usersProvider->save(update) Finished");
        } else {
            // Insert new record
            await new Promise((resolve, reject) => {
                db.serialize(() => {
                    logger.log("usersProvider->save(insert) Started");
                    const uniqueUUID = uuid.v4();
                    logger.log("usersProvider->save Generated guid for new record: " + uniqueUUID);
                    db.prepare(`INSERT INTO users (email,displayName,guid,isDeleted) VALUES (?,?,?,?)`, [params.email,params.displayName, uniqueUUID, 0])
                      .run((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                      })
                      .finalize((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                          resolve();
                      });
                });
            });
            logger.log("usersProvider->save(insert) Finished");
        }
        db.close();
        return "ok";
    } catch (error) {
        logger.error("usersProvider->save error: " + error.message);
        throw error;
    }
}


// save
async function updatePwd(params) {
    logger.log("usersProvider->updatePwd Started: " + JSON.stringify(params));
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        if (params.id > 0) {
            // Update existing record
            await new Promise((resolve, reject) => {
                db.serialize(() => {
                    logger.log("usersProvider->updatePwd(update) Started");
                    db.prepare(`UPDATE users SET password=? WHERE id=?`, [params.password,params.id])
                      .run((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                      })
                      .finalize((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                          resolve();
                      });
                });
            });
            logger.log("usersProvider->updatePwd(update) Finished");
        } else {
            // Insert new record
            await new Promise((resolve, reject) => {
                db.serialize(() => {
                    logger.log("usersProvider->updatePwd(insert) Started");
                    const uniqueUUID = uuid.v4();
                    logger.log("usersProvider->updatePwd Generated guid for new record: " + uniqueUUID);
                    db.prepare(`INSERT INTO users (,guid,isDeleted) VALUES (,?,?)`, [, uniqueUUID, 0])
                      .run((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                      })
                      .finalize((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                          resolve();
                      });
                });
            });
            logger.log("usersProvider->updatePwd(insert) Finished");
        }
        db.close();
        return "ok";
    } catch (error) {
        logger.error("usersProvider->updatePwd error: " + error.message);
        throw error;
    }
}


// logic delete
async function deleteLogic(params) {
    logger.log("usersProvider->deleteLogic Started: " + JSON.stringify(params));
    try {
        const db = await new sqlite3.Database(dbHelper.ReturnDBPath());
        if (params.guid != null && params.guid !== '') {
            await new Promise((resolve, reject) => {
                db.serialize(() => {
                    logger.log("usersProvider->deleteLogic(logic delete) Started");

                    db.prepare(`UPDATE users SET isDeleted=1 WHERE guid=?`, [params.guid])
                      .run((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                      })
                      .finalize((err) => {
                          if (err) {
                              logger.error(err.message);
                              return reject(err);
                          }
                          resolve();
                      });
                });
            });
            db.close();
            logger.log("usersProvider->deleteLogic(logic delete) Finished");
            return "ok";
        } else {
            throw new Error("Invalid GUID");
        }
    } catch (error) {
        logger.error("usersProvider->deleteLogic error: " + error.message);
        throw error;
    }
}




module.exports = { getIdByGuid,getByGuid,listForGrid,listForDropdown,listAll,save,updatePwd,deleteLogic, }